language: android
dist: trusty

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
  global:
    - ANDROID_API=29
    - ANDROID_BUILD_TOOLS=29.0.2

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools
    - build-tools-${ANDROID_BUILD_TOOLS}
    - android-${ANDROID_API}

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-29"
  - chmod +x gradlew

notifications:
  slack: raxdenstudiosgroup:${SLACK_TOKEN}

stages:
  - test
  - publish

jobs:
  include:
    - stage: test
      name: "test"
      if: branch = master AND (type = push OR type = pull_request)
      script: ./gradlew --console=plain detekt libraries:preferences:testReleaseUnitTest
