# This is a basic workflow to help you get started with Actions

name: Continuous Integration

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Run Build Project
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build Project
        run: bash ./gradlew --console=plain libraries:advanced-preferences:assembleRelease
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    needs: build
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests
        run: bash ./gradlew --console=plain libraries:advanced-preferences:detekt libraries:advanced-preferences:testReleaseUnitTest

  deploy:
    name: Run Deploy Library
    runs-on: ubuntu-latest
    environment: release_environment

    needs: test
    if: startsWith(github.ref, 'refs/tags')
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Deploy library
        env:
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          BINTRAY_REPOSITORY: ${{ secrets.BINTRAY_REPOSITORY }}
        run: bash ./gradlew clean publish bintrayUpload
